(()=>{'use strict';
const T=window.TST,$=T.$,$$=T.$$;
function collect(form){const a={};T.FIELDS.forEach(n=>a[n]=form.elements[n]?.value||'u');return a}
function restore(form,a={}){T.FIELDS.forEach(n=>{const v=a[n];if(!v)return;const el=form.querySelector(`input[name="${n}"][value="${v}"]`);if(el)el.checked=true})}
function answered(form){return T.FIELDS.filter(n=>(form.elements[n]?.value||'u')!=='u').length}
function saveAnalysis(form){const project=form.project.value.trim()||'Genel';let no=form.analysisNo.value.trim(),err=$('#formError');err.textContent='';if(!no)no=T.state.edit?(T.state.records.find(r=>r.id===T.state.edit)?.analysisNo||T.nextNo(project)):T.nextNo(project);if(T.state.records.some(r=>r.id!==T.state.edit&&r.project===project&&r.analysisNo===no)){err.textContent=`“${no}” bu projede zaten var.`;form.analysisNo.focus();return null}const a=collect(form),result=T.evaluate(a),stamp=T.now();let rec=T.state.edit?T.state.records.find(r=>r.id===T.state.edit):null;if(rec)Object.assign(rec,{project,analysisNo:no,note:form.note.value.trim(),answers:a,result,updatedAt:stamp});else{rec={id:T.uid(),project,analysisNo:no,note:form.note.value.trim(),answers:a,result,createdAt:stamp,updatedAt:stamp};T.state.records.push(rec);T.state.edit=rec.id}T.save();form.analysisNo.value=no;return rec}
async function shareRecords(records){if(!records.length){T.toast('Dışa aktarılacak analiz yok.');return}const payload={app:T.APP,version:T.VERSION,exportedAt:T.now(),recordCount:records.length,records},json=JSON.stringify(payload,null,2),name=`Tasiyici_Sistem_Analizleri_${new Date().toISOString().slice(0,10)}.json`;try{const file=new File([json],name,{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Taşıyıcı Sistem Analizleri',files:[file]});return}}catch(e){if(e?.name==='AbortError')return}const url=URL.createObjectURL(new Blob([json],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);T.toast('Analiz dosyası oluşturuldu.')}
function uniqueNo(project,proposed){let base=(proposed||'').trim()||T.nextNo(project),candidate=base,n=2;while(T.state.records.some(x=>x.project===project&&x.analysisNo===candidate))candidate=`${base}_${n++}`;return candidate}
function importData(data){if(!data||!Array.isArray(data.records))throw Error('Geçerli analiz kayıt listesi bulunamadı.');let added=0,updated=0,renamed=0,skipped=0;for(const raw of data.records){if(!raw||typeof raw!=='object'||!raw.id||!raw.answers){skipped++;continue}const old=T.state.records.find(r=>r.id===raw.id);if(old){if((raw.updatedAt||'')>(old.updatedAt||'')){Object.assign(old,raw);old.project=(old.project||'Genel').trim()||'Genel';old.result=T.evaluate(old.answers||{});updated++}else skipped++;continue}const r=typeof structuredClone==='function'?structuredClone(raw):JSON.parse(JSON.stringify(raw));r.project=(r.project||'Genel').trim()||'Genel';const before=(r.analysisNo||'').trim(),after=uniqueNo(r.project,before||T.nextNo(r.project));if(after!==before)renamed++;r.analysisNo=after;r.result=T.evaluate(r.answers||{});r.createdAt=r.createdAt||T.now();r.updatedAt=r.updatedAt||r.createdAt;T.state.records.push(r);added++}T.save();return {added,updated,renamed,skipped}}
async function copyText(id){const rec=T.state.records.find(r=>r.id===id),r=rec?.result;if(!rec)return;const text=[`Proje: ${rec.project}`,`Analiz: ${rec.analysisNo}`,`Sonuç: ${r.headline}`,`Güven: ${r.confidence}`,'',...r.ranked.slice(0,5).map((x,i)=>`${i+1}. ${x[0]} — ${x[1]} puan`),'','Not: Bu çıktı saha ön sınıflandırmasıdır; deprem güvenliği veya riskli yapı kararı değildir.'].join('\n');try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();if(!document.execCommand('copy'))throw Error();ta.remove()}T.toast('Sonuç panoya kopyalandı.')}catch{T.toast('Kopyalama bu tarayıcıda kullanılamıyor.') }}
function closeModal(){const host=$('#modalHost');if(!host.hasChildNodes())return;host.innerHTML='';T.state.lastFocus?.focus?.();T.state.lastFocus=null}
function wireModal(layer){layer.addEventListener('pointerdown',e=>{if(e.target===layer)closeModal()});$$('[data-close]',layer).forEach(b=>b.onclick=closeModal);layer.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeModal();return}if(e.key!=='Tab')return;const items=$$('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]',layer);if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}})}
function modal(title,text,action,fn,danger=true){T.state.lastFocus=document.activeElement;$('#modalHost').innerHTML=`<div class="modalLayer"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="dialogTitle"><div class="modalhead"><h2 id="dialogTitle">${T.esc(title)}</h2><button class="iconbtn" data-close aria-label="Pencereyi kapat">×</button></div><div class="modalbody"><p>${T.esc(text)}</p></div><div class="modalfoot"><button class="btn2" data-close>Vazgeç</button><button class="${danger?'dangerbtn':'btn'}" id="modalAction">${T.esc(action)}</button></div></section></div>`;const layer=$('.modalLayer');wireModal(layer);$('#modalAction').onclick=()=>{closeModal();fn()};requestAnimationFrame(()=>$('#modalAction')?.focus())}
function applySettings(){const s=T.get(T.SET,{large:false,contrast:false});document.body.classList.toggle('large-text',!!s.large);document.body.classList.toggle('high-contrast',!!s.contrast)}
function settings(){const s=T.get(T.SET,{large:false,contrast:false});T.state.lastFocus=document.activeElement;$('#modalHost').innerHTML=`<div class="modalLayer"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="settingsTitle"><div class="modalhead"><h2 id="settingsTitle">Ayarlar</h2><button class="iconbtn" data-close aria-label="Pencereyi kapat">×</button></div><div class="modalbody"><label><input id="large" type="checkbox" ${s.large?'checked':''}> Büyük metin</label><br><br><label><input id="contrast" type="checkbox" ${s.contrast?'checked':''}> Artırılmış sınır kontrastı</label><div class="divider"></div><button class="dangerbtn" id="clearAll">Analiz hafızasını sil</button></div></section></div>`;const layer=$('.modalLayer');wireModal(layer);$('#large').onchange=e=>{s.large=e.target.checked;T.set(T.SET,s);applySettings()};$('#contrast').onchange=e=>{s.contrast=e.target.checked;T.set(T.SET,s);applySettings()};$('#clearAll').onclick=()=>{closeModal();clearAll()};requestAnimationFrame(()=>$('#large')?.focus())}
function clearAll(){modal('Analiz hafızasını sil','Bu araca ait bütün yerel analizler ve tercihler bu cihazdan silinecek. Bu işlem geri alınamaz.','Tümünü Sil',()=>{T.state.records=[];T.state.edit=null;T.state.search='';T.state.project='';if(T.CAN_STORE){localStorage.removeItem(T.DB);localStorage.removeItem(T.SET)}try{sessionStorage.removeItem(T.DB);sessionStorage.removeItem(T.SET)}catch{}applySettings();T.go('#/home');T.toast('Bu araca ait yerel hafıza temizlendi.')})}
function bind(){const form=$('#analysisForm');if(form){const rec=T.state.edit?T.state.records.find(r=>r.id===T.state.edit):null;if(rec)restore(form,rec.answers);const update=()=>{$('#answeredCount').textContent=answered(form)+' ayırt edici yanıt'};form.addEventListener('change',update);update();form.onsubmit=e=>{e.preventDefault();const rec=saveAnalysis(form);if(rec){T.toast('Analiz kaydedildi.');T.go('#/result/'+encodeURIComponent(rec.id))}};$('#resetForm').onclick=()=>modal('Formu temizle','Soru yanıtları temizlenecek; proje ve analiz kimliği korunacak.','Temizle',()=>{T.FIELDS.forEach(n=>$$(`input[name="${n}"]`,form).forEach(x=>x.checked=false));update()},false)}
 $('#archiveSearch')?.addEventListener('input',e=>{T.state.search=e.target.value;T.render()});$('#archiveProject')?.addEventListener('change',e=>{T.state.project=e.target.value;T.render()});$$('[data-open]').forEach(b=>b.onclick=()=>T.go('#/result/'+encodeURIComponent(b.dataset.open)));$$('[data-edit]').forEach(b=>b.onclick=()=>T.go('#/analysis/'+encodeURIComponent(b.dataset.edit)));$$('[data-copy]').forEach(b=>b.onclick=()=>copyText(b.dataset.copy));$$('[data-print]').forEach(b=>b.onclick=()=>window.print());$$('[data-export]').forEach(b=>b.onclick=()=>shareRecords(T.state.records));$$('[data-export-one]').forEach(b=>b.onclick=()=>shareRecords(T.state.records.filter(r=>r.id===b.dataset.exportOne)));$$('[data-import]').forEach(b=>b.onclick=()=>$('#importInput').click());$$('[data-delete]').forEach(b=>b.onclick=()=>{const r=T.state.records.find(x=>x.id===b.dataset.delete);modal('Analizi sil',`${r?.analysisNo||'Bu analiz'} kalıcı olarak silinecek.`,'Sil',()=>{T.state.records=T.state.records.filter(x=>x.id!==b.dataset.delete);T.save();T.go('#/archive')})});$$('[data-clear]').forEach(b=>b.onclick=clearAll)}
T.render=()=>{const route=T.route();let html='',nav='';if(route==='#/home'){html=T.home();nav='home'}else if(route==='#/archive'){html=T.archive();nav='archive'}else if(route==='#/reference'){html=T.reference();nav='reference'}else if(route==='#/help')html=T.help();else if(route==='#/analysis/new')html=T.analysis(null);else if(route.startsWith('#/analysis/'))html=T.analysis(decodeURIComponent(route.slice(11)));else if(route.startsWith('#/result/'))html=T.result(decodeURIComponent(route.slice(9)));else{return T.go('#/home')}$('#app').innerHTML=html;T.nav(nav);bind();window.scrollTo({top:0,behavior:'auto'})};
function closeSearch(){const box=$('#searchResults');box.hidden=true;$('#globalSearch').setAttribute('aria-expanded','false')}
function drawSearch(q=''){const box=$('#searchResults'),needle=T.lower(q.trim());let list=[...T.state.records].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));if(needle)list=list.filter(r=>T.lower([r.analysisNo,r.project,r.note,r.result?.headline].join(' ')).includes(needle));else list=list.slice(0,6);box.innerHTML=list.length?list.slice(0,10).map(r=>`<button class="resultitem" data-sid="${T.esc(r.id)}"><span><strong>${T.esc(r.analysisNo)}</strong><small>${T.esc(r.project)} · ${T.esc(r.result?.headline||'Sonuç yok')}</small></span><span aria-hidden="true">›</span></button>`).join(''):'<div class="help" style="padding:14px">Kayıt bulunamadı.</div>';box.hidden=false;$('#globalSearch').setAttribute('aria-expanded','true');$$('[data-sid]',box).forEach(b=>b.onclick=()=>{closeSearch();T.go('#/result/'+encodeURIComponent(b.dataset.sid))})}
$('#globalSearch').addEventListener('focus',e=>drawSearch(e.target.value));$('#globalSearch').addEventListener('input',e=>drawSearch(e.target.value));document.addEventListener('pointerdown',e=>{if(!e.target.closest('.search'))closeSearch()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}else if(e.key==='Escape'&&!$('#modalHost').hasChildNodes())closeSearch()});$('#settingsBtn').onclick=settings;
$('#importInput').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const data=JSON.parse(await file.text());if(data.app&&data.app!==T.APP)throw Error('Dosya bu uygulamaya ait değil.');const r=importData(data);T.toast(`${r.added} yeni, ${r.updated} güncellenen kayıt içe alındı${r.renamed?`; ${r.renamed} analiz numarası yeniden adlandırıldı`:''}.`);T.render()}catch(err){modal('İçe aktarma başarısız',err?.message||'Dosya okunamadı.','Tamam',()=>{},false)}};
window.addEventListener('hashchange',T.render);T.load();applySettings();if(!location.hash)location.hash='#/home';else T.render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
