(()=>{'use strict';
const T=window.TST={};
T.$=(s,r=document)=>r.querySelector(s);T.$$=(s,r=document)=>[...r.querySelectorAll(s)];
T.DB='ari_tasiyici_analiz_v4';T.SET='ari_tasiyici_settings_v4';T.APP='ARI_Tasiyici_Sistem_Tespit';T.VERSION=4;
T.FIELDS=window.TasiyiciEngine.fields;T.evaluate=window.TasiyiciEngine.evaluate;
T.state={records:[],edit:null,search:'',project:'',lastFocus:null};
T.CAN_STORE=(()=>{try{localStorage.setItem('__t','1');localStorage.removeItem('__t');return true}catch{return false}})();
T.get=(k,f)=>{if(!T.CAN_STORE)return f;try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}};
T.set=(k,v)=>{if(!T.CAN_STORE)return false;try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
T.esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
T.lower=s=>String(s??'').toLocaleLowerCase('tr-TR');T.now=()=>new Date().toISOString();
T.fmt=x=>{try{return new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}catch{return x||'—'}};
T.uid=()=>crypto?.randomUUID?.()||'a_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9);
T.load=()=>{T.state.records=T.get(T.DB,{records:[]}).records||[]};T.save=()=>T.set(T.DB,{app:T.APP,version:T.VERSION,records:T.state.records});
T.projects=()=>[...new Set(T.state.records.map(r=>r.project||'Genel'))].sort((a,b)=>a.localeCompare(b,'tr'));
T.nextNo=project=>{const used=new Set(T.state.records.filter(r=>r.project===project).map(r=>r.analysisNo));let n=1;while(used.has('Analiz_'+n))n++;return 'Analiz_'+n};
T.toast=t=>{const e=document.createElement('div');e.className='toast';e.textContent=t;T.$('#toasts').append(e);setTimeout(()=>e.remove(),3200)};
T.route=()=>location.hash||'#/home';T.go=h=>{location.hash===h?T.render():location.hash=h};
T.nav=n=>T.$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===n));
})();
