(()=>{'use strict';
const SYSTEMS=['Betonarme Karkas','Çelik Karkas','Yığma Kâgir','Yığma Yarı Kâgir','Ahşap','Kerpiç','Taş Duvarlı','Basit Bina'];
const FIELDS=['frame','frameMat','columns','bearingWalls','wallMat','wallThick','floor','floorSupport','wideOpen','steelRoofOnly','woodFrame','adobeVisible','stoneMortar','simple','mixedSystem'];
function evaluate(a){const v=n=>a[n]||'u',s={};SYSTEMS.forEach(x=>s[x]=0);const ev=[],cf=[],add=(n,p)=>s[n]+=p;
 const frame=v('frame'),fm=v('frameMat'),cols=v('columns'),bw=v('bearingWalls'),wm=v('wallMat'),wt=v('wallThick'),floor=v('floor'),fs=v('floorSupport'),wide=v('wideOpen'),steel=v('steelRoofOnly'),wood=v('woodFrame'),adobe=v('adobeVisible'),mortar=v('stoneMortar'),simple=v('simple'),mixed=v('mixedSystem');
 if(frame==='y'){add('Betonarme Karkas',4);add('Çelik Karkas',4);add('Ahşap',2);ev.push('Tekrarlayan kolon-kiriş iskeleti görülüyor.')}if(frame==='n'){add('Yığma Kâgir',3);add('Yığma Yarı Kâgir',2);add('Kerpiç',2);add('Taş Duvarlı',2)}
 if(fm==='rc'){add('Betonarme Karkas',9);ev.push('İskelet elemanları betonarme karakterinde.')}if(fm==='steel'){add('Çelik Karkas',8);ev.push('Çelik profil iskelet elemanları görülüyor.')}if(fm==='wood'){add('Ahşap',7);add('Yığma Yarı Kâgir',1)}if(fm==='mixed'){add('Basit Bina',2);add('Yığma Yarı Kâgir',2);cf.push('İskelet malzemesi karma olarak işaretlendi.')}
 if(cols==='y'){add('Betonarme Karkas',3);add('Çelik Karkas',3);add('Ahşap',2);ev.push('Bağımsız kolon sürekliliği gözleniyor.')}if(cols==='n'){add('Yığma Kâgir',2);add('Kerpiç',1);add('Taş Duvarlı',1)}
 if(bw==='y'){add('Yığma Kâgir',5);add('Yığma Yarı Kâgir',4);add('Kerpiç',4);add('Taş Duvarlı',4);ev.push('Kalın ve sürekli taşıyıcı duvar izlenimi var.')}if(bw==='n'){add('Betonarme Karkas',2);add('Çelik Karkas',2);add('Ahşap',1)}
 if(wm==='stone'){add('Taş Duvarlı',7);add('Yığma Kâgir',3);add('Yığma Yarı Kâgir',2);ev.push('Ana duvar malzemesi taş.')}if(wm==='brick'){add('Yığma Kâgir',5);add('Yığma Yarı Kâgir',3);if(frame==='y')add('Betonarme Karkas',1)}if(wm==='adobe'){add('Kerpiç',10);ev.push('Toprak/kerpiç esaslı duvar görülüyor.')}if(wm==='wood')add('Ahşap',7);if(wm==='mixed'){add('Basit Bina',3);add('Yığma Yarı Kâgir',2)}
 if(wt==='30_49'){['Yığma Kâgir','Yığma Yarı Kâgir','Kerpiç','Taş Duvarlı'].forEach(x=>add(x,2))}if(wt==='50p'){add('Taş Duvarlı',3);add('Kerpiç',3);add('Yığma Kâgir',2)}if(wt==='lt20'&&bw!=='y'){add('Betonarme Karkas',1);add('Çelik Karkas',1)}if(mortar==='mud'&&wm==='stone'){add('Taş Duvarlı',6);ev.push('Taş örgü çamur/toprak harçlı görünüyor.')}if(mortar==='mortar'&&wm==='stone')add('Yığma Kâgir',3)
 if(floor==='rc'){add('Betonarme Karkas',3);add('Yığma Kâgir',2);ev.push('Betonarme döşeme görüldü; tek başına karkas kanıtı sayılmadı.')}if(floor==='wood'){add('Yığma Yarı Kâgir',5);add('Ahşap',3);add('Taş Duvarlı',1)}if(floor==='steel')add('Çelik Karkas',3);if(floor==='mixed'){add('Yığma Yarı Kâgir',2);add('Basit Bina',2)}
 if(fs==='frame'){add('Betonarme Karkas',6);add('Çelik Karkas',5);add('Ahşap',3);ev.push('Döşeme yükü iskelete aktarılıyor.')}if(fs==='walls'){add('Yığma Kâgir',7);add('Yığma Yarı Kâgir',5);add('Kerpiç',4);add('Taş Duvarlı',4);ev.push('Döşeme yükü esas olarak duvarlara aktarılıyor.')}if(bw==='y'&&fs==='walls'&&floor==='rc')add('Yığma Kâgir',6);if(bw==='y'&&fs==='walls'&&floor==='wood')add('Yığma Yarı Kâgir',7);if(wide==='y'){add('Betonarme Karkas',2);add('Çelik Karkas',2)}
 if(steel==='y'){s['Çelik Karkas']=Math.max(0,s['Çelik Karkas']-5);ev.push('Çelik yalnız çatıda; tek başına çelik karkas kanıtı değil.')}if(steel==='n'&&fm==='steel')add('Çelik Karkas',5);if(wood==='y'){add('Ahşap',9);ev.push('Ahşap dikme/çaprazlar esas taşıyıcı iskelet gibi devam ediyor.')}if(wood==='n'&&floor==='wood'&&bw==='y')add('Yığma Yarı Kâgir',3);if(adobe==='y'){add('Kerpiç',10);ev.push('Sıva altında kerpiç blok açıkça seçiliyor.')}if(adobe==='n'&&wm==='adobe'){s['Kerpiç']=Math.max(0,s['Kerpiç']-2);cf.push('Duvar kerpiç seçildi ancak açık kerpiç bloğu gözlenmedi.')}
 if(simple==='y'){add('Basit Bina',10);ev.push('Yapı düşük standartlı, basit/karma yapı karakterinde.')}if(simple==='n')s['Basit Bina']=Math.max(0,s['Basit Bina']-2)
 if(fm==='rc'&&cols==='y'&&fs==='frame')add('Betonarme Karkas',7);if(fm==='steel'&&cols==='y'&&fs==='frame'&&steel!=='y')add('Çelik Karkas',7);if(wm==='stone'&&bw==='y'&&fs==='walls')add('Taş Duvarlı',5);if(wm==='brick'&&bw==='y'&&fs==='walls'&&floor==='rc')add('Yığma Kâgir',5);if((wm==='stone'||wm==='brick')&&bw==='y'&&fs==='walls'&&floor==='wood')add('Yığma Yarı Kâgir',5)
 if(frame==='y'&&bw==='y')cf.push('Hem karkas iskelet hem taşıyıcı duvar işareti var; karma veya yanlış gözlem olasılığı kontrol edilmeli.');if(fs==='frame'&&bw==='y')cf.push('Döşeme iskelete oturuyor ancak duvarlar taşıyıcı olarak işaretlenmiş.');if(fs==='walls'&&(fm==='rc'||fm==='steel')&&cols==='y')cf.push('Belirgin karkas elemanlarına rağmen döşeme duvara oturuyor işaretlendi.');if(steel==='y'&&fm==='steel'&&cols==='n')cf.push('Çelik elemanlar yalnız çatı sistemi olabilir.');if(mixed==='y')cf.unshift('Katlar veya bina bölümleri arasında farklı taşıyıcı sistem bulunduğu bildirildi.')
 Object.keys(s).forEach(k=>s[k]=Math.max(0,s[k]));const ranked=Object.entries(s).sort((x,y)=>y[1]-x[1]),top=ranked[0],second=ranked[1],margin=top[1]-second[1],answered=FIELDS.filter(n=>v(n)!=='u').length;let headline,confidence,level;
 if(mixed==='y'){headline='Karma taşıyıcı sistem olası';confidence='Tek sınıfa zorlamayın';level='mixed'}else if(answered<5||top[1]<8){headline='Sonuç için veri yetersiz';confidence='Düşük güven';level='low'}else if(margin<=2){headline=top[0]+' / '+second[0]+' arasında belirsiz';confidence='İki aday birbirine çok yakın';level='ambiguous'}else{headline=top[0];if(margin>=7&&top[1]>=15){confidence='Yüksek olasılıklı ön sınıflandırma';level='high'}else if(margin>=4){confidence='Orta olasılıklı ön sınıflandırma';level='medium'}else{confidence='Düşük olasılıklı ön sınıflandırma';level='low'}}
 const pair=[top[0],second[0]].sort().join('|'),checks={'Betonarme Karkas|Yığma Kâgir':'Bodrum, otopark veya merdiven altında döşemenin kolon-kiriş çerçevesine mi, kalın duvara mı oturduğunu kontrol edin.','Yığma Kâgir|Yığma Yarı Kâgir':'Döşeme altını veya çatı arasını kontrol edin. Ahşap kirişli döşeme yarı kâgir olasılığını artırır.','Taş Duvarlı|Yığma Kâgir':'Taş örgünün harcını, duvar kalınlığını ve döşemenin duvara oturup oturmadığını kontrol edin.','Betonarme Karkas|Çelik Karkas':'Kolon ve kiriş malzemesini doğrulayın. Çelik yalnız çatıda ise tüm bina çelik karkas sayılmaz.','Ahşap|Yığma Yarı Kâgir':'Ahşap dikme ve çaprazların ana iskelet olarak katlar boyunca devam edip etmediğine bakın.'};
 return {scores:s,ranked,answered,margin,headline,confidence,level,evidence:ev,conflicts:cf,nextCheck:checks[pair]||'Döşemenin neye oturduğunu ve esas düşey taşıyıcının kolon mu, sürekli duvar mı olduğunu doğrulayın.'}}
window.TasiyiciEngine={systems:SYSTEMS,fields:FIELDS,evaluate};
})();
