(()=>{'use strict';const T=window.TST,{esc,fmt}=T;
T.sections=[
['01','İskeleti bulun','Önce yapının yükleri kolon-kiriş iskeletiyle mi taşıdığına dair izleri arayın.',[
 ['frame','Katlar boyunca tekrar eden kolon-kiriş iskeleti seçiliyor mu?',[['y','Evet'],['n','Hayır'],['u','Bilmiyorum']],'Bodrum, otopark, cephe veya merdiven boşluğunda süreklilik arayın.'],
 ['frameMat','Görünen iskelet elemanının malzemesi nedir?',[['rc','Betonarme'],['steel','Çelik'],['wood','Ahşap'],['mixed','Karma'],['u','Bilmiyorum']]],
 ['columns','Bağımsız kolonlar alt kattan üst kata süreklilik gösteriyor mu?',[['y','Evet'],['n','Hayır'],['u','Bilmiyorum']]]]],
['02','Duvarı okuyun','Duvarın yalnız bölücü mü, yoksa yük taşıyan ana eleman mı olduğunu anlamaya çalışın.',[
 ['bearingWalls','Kalın ve katlar boyunca devam eden duvarlar ana taşıyıcı gibi mi?',[['y','Evet'],['n','Hayır'],['u','Bilmiyorum']]],
 ['wallMat','Duvarın görülebilen ana malzemesi nedir?',[['stone','Taş'],['brick','Tuğla / briket'],['adobe','Kerpiç'],['wood','Ahşap çatkı'],['mixed','Karma'],['u','Bilmiyorum']]],
 ['wallThick','Taşıyıcı olduğu düşünülen duvar yaklaşık kaç cm?',[['lt20','< 20 cm'],['20_29','20–29 cm'],['30_49','30–49 cm'],['50p','50 cm +'],['u','Ölçemiyorum']]],
 ['stoneMortar','Taş duvar varsa taşlar arasındaki bağlayıcı neye benziyor?',[['mud','Çamur / toprak'],['mortar','Kireçli / çimentolu'],['u','Bilmiyorum / taş yok']]]]],
['03','Döşemenin nereye oturduğunu bulun','Karkas-yığma ayrımında en değerli gözlemlerden biridir.',[
 ['floor','Döşeme veya tavan taşıyıcı sistemi neye benziyor?',[['rc','Betonarme'],['wood','Ahşap kirişli'],['steel','Çelik kirişli'],['mixed','Karma'],['u','Bilmiyorum']]],
 ['floorSupport','Döşeme esas olarak neyin üzerine oturuyor?',[['frame','Kolon-kiriş iskeletine'],['walls','Kalın duvarlara'],['u','Anlaşılamıyor']],'Betonarme döşeme görmek tek başına betonarme karkas anlamına gelmez.'],
 ['wideOpen','Zemin katta kalın taşıyıcı duvar olmadan geniş dükkân, garaj veya otopark açıklığı var mı?',[['y','Evet'],['n','Hayır'],['u','Bilmiyorum']]]]],
['04','Özel malzeme işaretlerini kontrol edin','Çelik çatı, ahşap iskelet ve kerpiç gibi ayırt edici ayrıntıları ayrıca doğrulayın.',[
 ['steelRoofOnly','Gördüğünüz çelik yalnızca çatı makası veya çatı taşıyıcısı mı?',[['y','Evet, yalnız çatıda'],['n','Hayır, iskelette de'],['u','Bilmiyorum / çelik yok']]],
 ['woodFrame','Ahşap dikme, kiriş veya çaprazlar esas iskelet olarak kat boyunca devam ediyor mu?',[['y','Evet'],['n','Hayır'],['u','Bilmiyorum']]],
 ['adobeVisible','Sıva altında toprak esaslı, kolay aşınan kerpiç blok açıkça görülüyor mu?',[['y','Evet'],['n','Hayır'],['u','Bilmiyorum']]]]],
['05','Karma yapı ve son kontrol','Sistemi tek kutuya zorlamadan önce yapının farklı dönemlerde değişip değişmediğini kontrol edin.',[
 ['simple','Yapı baraka, sundurma, müştemilat veya düşük standartlı karma yapı karakterinde mi?',[['y','Evet'],['n','Hayır'],['u','Bilmiyorum']],'“Basit bina” burada saha/değerleme envanteri sınıfı olarak ele alınır.'],
 ['mixedSystem','Katlar veya bina bölümleri arasında açıkça farklı taşıyıcı sistemler var mı?',[['y','Evet'],['n','Hayır'],['u','Bilmiyorum']],'Örn. alt kat taş yığma, üst kat betonarme; betonarme üzerine çelik ek kat.']]]
];
T.choice=(n,v,l)=>`<span class="choice"><input id="${n}_${v}" type="radio" name="${n}" value="${v}"><label for="${n}_${v}">${l}</label></span>`;
T.questions=()=>T.sections.map(([no,title,desc,qs])=>`<section class="qsection"><div class="qhead"><div class="qnum">${no}</div><div><h2>${title}</h2><p>${desc}</p></div></div><div class="qrows">${qs.map(([n,t,opts,h])=>`<div class="qrow"><p class="qtitle">${t}</p>${h?`<span class="qhint">${h}</span>`:''}<div class="choices">${opts.map(o=>T.choice(n,o[0],o[1])).join('')}</div></div>`).join('')}</div></section>`).join('');
T.home=()=>{const recent=[...T.state.records].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')).slice(0,5);return `<header class="head"><div><p class="eyebrow">Kentsel Dönüşüm · Saha Karar Desteği</p><h1>Taşıyıcı Sistem Tespit</h1><p class="lead">Gördüğünüz kadarını işaretleyin. Sistem tek bir belirtiye göre hüküm vermez; yük yolu, duvar, döşeme ve malzeme işaretlerini birlikte değerlendirir.</p></div><div class="rowbtn"><a class="btn" href="#/analysis/new">Yeni tespit başlat</a><a class="btn2" href="#/archive">Analiz arşivi</a></div></header><div class="homegrid"><div><section class="soft feature"><p class="eyebrow">Çalışma ilkesi</p><h2>Malzemeyi değil, yükün izlediği yolu okuyun.</h2><p>Kolon-kiriş iskeleti, taşıyıcı duvar sürekliliği ve döşemenin neye oturduğu birlikte değerlendirilir. Bilgi eksikse sonuç kesinleştirilmez.</p><div class="rowbtn"><a class="btn" href="#/analysis/new">Sahada yeni analiz</a><a class="btn2" href="#/reference">Hızlı referans</a></div></section><div class="quickgrid"><div class="quick"><strong>Tek sayfa tespit</strong><p>15 soru aynı yüzeyde.</p></div><div class="quick"><strong>Yerel arşiv</strong><p>Analizler bu cihazda proje bazında saklanır.</p></div><div class="quick"><strong>Taşınabilir veri</strong><p>JSON ile cihazlar arasında birleştirilebilir.</p></div></div><div class="sectionline"><h2>Son analizler</h2><span class="help">${T.state.records.length} toplam kayıt</span></div>${recent.length?`<section class="panel" style="padding:0 20px">${recent.map(r=>`<a class="recent" href="#/result/${encodeURIComponent(r.id)}"><span><strong>${esc(r.analysisNo)}</strong><small>${esc(r.project)} · ${esc(r.result?.headline||'Sonuç yok')}</small></span><span class="help">${fmt(r.updatedAt)}</span></a>`).join('')}</section>`:`<div class="empty">Bu cihazda henüz kayıtlı analiz yok.</div>`}</div><aside><section class="panel summary"><p class="eyebrow">Yerel hafıza</p><div class="n">${T.state.records.length}</div><div class="help">kayıtlı analiz</div><div class="divider"></div><div class="n" style="font-size:28px">${T.projects().length}</div><div class="help">proje grubu</div><div class="divider"></div><span class="status ${T.CAN_STORE?'done':'warn'}">${T.CAN_STORE?'Yerel kayıt kullanılabilir':'Yerel kayıt kullanılamıyor'}</span></section></aside></div>`};
T.analysis=id=>{const rec=id?T.state.records.find(r=>r.id===id):null;T.state.edit=rec?.id||null;return `<header class="head"><div><p class="eyebrow">${rec?'Kayıtlı Analiz':'Yeni Analiz'}</p><h1>${rec?esc(rec.analysisNo):'Yeni taşıyıcı sistem tespiti'}</h1><p class="lead">Soruların tamamı bu sayfada. Emin olmadığınız soruyu boş bırakabilir veya Bilmiyorum seçebilirsiniz.</p></div><a class="btn2" href="#/archive">Arşive dön</a></header><form id="analysisForm"><div class="analysis-layout"><aside class="panel analysis-meta"><p class="eyebrow">Analiz Kimliği</p><div class="formfield"><label for="project">Proje</label><input id="project" name="project" type="text" placeholder="Örn. Elmadağ Planlama" value="${esc(rec?.project==='Genel'?'':rec?.project||'')}"><span class="help">Boşsa Genel grubuna kaydedilir.</span></div><div class="formfield"><label for="analysisNo">Analiz numarası <span class="help">(isteğe bağlı)</span></label><input id="analysisNo" name="analysisNo" type="text" placeholder="Boşsa otomatik atanır" value="${esc(rec?.analysisNo||'')}"></div><div class="formfield"><label for="note">Not / saha referansı</label><textarea id="note" name="note" placeholder="Ada-parsel, adres veya kısa not…">${esc(rec?.note||'')}</textarea></div><div id="formError" class="help" role="alert"></div><div class="divider"></div><span class="status orange">${rec?'Kayıt düzenleniyor':'Henüz kaydedilmedi'}</span><p class="help" style="margin-top:14px">Hesaplama ve kayıt bu cihazda yapılır. Yapay zekâ veya sunucu kullanılmaz.</p></aside><section>${T.questions()}<div class="formfinish"><div><strong id="answeredCount">0 ayırt edici yanıt</strong><div class="help">Boşlar bilinmiyor kabul edilir.</div></div><div class="rowbtn"><button class="btn2" id="resetForm" type="button">Formu temizle</button><button class="btn" type="submit">Sonucu hesapla ve kaydet</button></div></div></section></div></form>`};
T.archive=()=>{let list=[...T.state.records].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));const q=T.lower(T.state.search);if(q)list=list.filter(r=>T.lower([r.analysisNo,r.project,r.note,r.result?.headline].join(' ')).includes(q));if(T.state.project)list=list.filter(r=>r.project===T.state.project);return `<header class="head"><div><p class="eyebrow">Yerel Analiz Hafızası</p><h1>Analiz Arşivi</h1><p class="lead">Bu cihazdaki analizleri proje bazında görüntüleyin; JSON dosyalarıyla farklı cihazlardaki kayıtları birleştirin.</p></div><div class="rowbtn"><a class="btn" href="#/analysis/new">Yeni tespit</a><button class="btn2" data-export>Tümünü paylaş / dışa aktar</button><button class="btn2" data-import>Dosyadan içe aktar</button></div></header><div class="archivebar"><input id="archiveSearch" type="search" placeholder="Analiz, proje, sonuç veya not ara…" value="${esc(T.state.search)}"><select id="archiveProject"><option value="">Tüm projeler</option>${T.projects().map(p=>`<option ${p===T.state.project?'selected':''}>${esc(p)}</option>`).join('')}</select><span class="help">${list.length} / ${T.state.records.length} kayıt</span></div>${list.length?`<div class="data"><table><thead><tr><th>Analiz</th><th>Proje</th><th>Sonuç</th><th>Güven</th><th>Güncelleme</th><th></th></tr></thead><tbody>${list.map(r=>`<tr><td><strong>${esc(r.analysisNo)}</strong><div class="help">${esc(r.note||'')}</div></td><td>${esc(r.project)}</td><td>${esc(r.result?.headline||'—')}</td><td><span class="status ${r.result?.level==='high'?'done':r.result?.level==='low'?'warn':'orange'}">${esc(r.result?.confidence||'—')}</span></td><td>${fmt(r.updatedAt)}</td><td><div class="tableactions"><button class="mini" data-open="${r.id}">Aç</button><button class="mini" data-delete="${r.id}">Sil</button></div></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Bu filtreye uyan kayıt bulunamadı.</div>`}<div class="sectionline"><h2>Veri yönetimi</h2></div><div class="rowbtn"><button class="btn2" data-export>Tüm analizleri dışa aktar</button><button class="btn2" data-import>Analiz dosyası içe aktar</button><button class="dangerbtn" data-clear>Analiz hafızasını sil</button></div><p class="help">Hafızayı sil bu araca ait tarayıcı kayıtlarını temizler; daha önce Dosyalar'a kaydettiğiniz JSON dosyalarını silemez.</p>`};
T.result=id=>{const rec=T.state.records.find(r=>r.id===id);if(!rec)return `<div class="empty">Analiz bulunamadı. <a href="#/archive">Arşive dön</a>.</div>`;const r=rec.result,max=Math.max(1,r.ranked[0][1]);return `<header class="head"><div><p class="eyebrow">Analiz Sonucu</p><h1>${esc(rec.analysisNo)}</h1><p class="lead">${esc(rec.project)}${rec.note?' · '+esc(rec.note):''}</p></div><div class="rowbtn result-actions"><button class="btn2" data-edit="${rec.id}">Yanıtları düzenle</button><button class="btn2" data-copy="${rec.id}">Sonucu kopyala</button><button class="btn2" data-print>Yazdır / PDF</button></div></header><section class="panel resulthead"><div><p class="eyebrow">Ön Sınıflandırma</p><h1>${esc(r.headline)}</h1><p class="lead">${r.answered} / ${T.FIELDS.length} soruda ayırt edici gözlem kullanıldı.</p></div><span class="status ${r.level==='high'?'done':r.level==='low'?'warn':'orange'}">${esc(r.confidence)}</span></section><div class="resultgrid"><section class="panel resultmain"><h2>Aday sıralaması</h2><div class="ranking">${r.ranked.slice(0,5).map(([n,sc],i)=>`<div class="rank"><strong>${i+1}. ${esc(n)}</strong><div class="track"><span style="width:${Math.round(sc/max*100)}%"></span></div><span class="score">${sc} puan</span></div>`).join('')}</div><div class="sectionline"><h2>Sonucu taşıyan gözlemler</h2></div><ul class="cleanlist">${(r.evidence.length?r.evidence:['Ayırt edici güçlü gözlem yok.']).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="sectionline"><h2>Çelişkiler / belirsizlikler</h2></div><ul class="cleanlist">${(r.conflicts.length?r.conflicts:['Belirgin çelişki saptanmadı.']).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><aside class="panel resultside"><div class="callout"><strong>Bir sonraki en değerli kontrol</strong><p>${esc(r.nextCheck)}</p></div><div class="callout warn" style="margin-top:16px"><strong>Mühendislik sınırı</strong><p>Bu sonuç deprem güvenliği veya riskli yapı kararı değildir.</p></div><div class="sectionline"><h2 style="font-size:17px">Kayıt işlemleri</h2></div><div class="rowbtn"><button class="btn2" data-export-one="${rec.id}">Bu analizi paylaş</button><button class="dangerbtn" data-delete="${rec.id}">Analizi sil</button></div></aside></div>`};
T.reference=()=>`<header class="head"><div><p class="eyebrow">Saha Referansı</p><h1>Taşıyıcı sistem ayrım tablosu</h1><p class="lead">Algoritmanın yerine geçmez; sahada hangi işaretin hangi sistemi desteklediğini hızlı hatırlatır.</p></div><a class="btn" href="#/analysis/new">Yeni tespit</a></header><div class="reference"><table><thead><tr><th>Sistem</th><th>Esas taşıyıcı</th><th>Güçlü saha işareti</th><th>Sık karışıklık</th></tr></thead><tbody>${[['Betonarme Karkas','Betonarme kolon, kiriş/perde','Süreklilik gösteren karkas; döşeme iskelete oturur','Tuğla dolgu duvarı taşıyıcı sanmak'],['Çelik Karkas','Çelik kolon ve kiriş','Çelik iskelet katlar boyunca sürer','Yalnız çelik çatıyı tüm yapı sanmak'],['Yığma Kâgir','Kâgir taşıyıcı duvar','Kalın sürekli duvar; döşeme duvara oturur','Betonarme döşeme nedeniyle karkas sanmak'],['Yığma Yarı Kâgir','Kâgir duvar + ahşap/karma döşeme','Taşıyıcı kâgir duvar + ahşap kirişli döşeme','Ahşap karkasla karıştırmak'],['Ahşap','Ahşap dikme/kiriş/çapraz','Ahşap iskelet katlar boyunca sürekli','Ahşap kaplamayı taşıyıcı sanmak'],['Kerpiç','Kerpiç taşıyıcı duvar','Toprak esaslı kalın blok','Sıvalı kerpici tuğla sanmak'],['Taş Duvarlı','Taş yığma duvar','Taş örgü, harç ve kalın duvar','Taş kaplamayı taşıyıcı sanmak'],['Basit Bina','Değişken','Düşük standartlı basit/karma karakter','Kesin mühendislik sistemi kabul etmek']].map(x=>`<tr><td><strong>${x[0]}</strong></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td></tr>`).join('')}</tbody></table></div>`;
T.help=()=>`<header class="head"><div><p class="eyebrow">Kullanım</p><h1>Yardım ve veri çalışma biçimi</h1><p class="lead">Araç çevrimdışı çalışır. Analiz kayıtları bu web adresi için ayrılmış yerel tarayıcı hafızasında tutulur.</p></div></header><div class="helpgrid">${[['Analiz numarası','Boş bırakılırsa proje içinde Analiz_1, Analiz_2… atanır.'],['Proje grubu','Aynı proje adıyla kaydedilen analizler arşivde birlikte filtrelenebilir.'],['Dışa aktarma','Destekleyen telefonda paylaşım sayfası açılır; aksi halde JSON indirilir.'],['İçe aktarma','Mevcut kayıtlar korunur; çakışmalar kimlik ve güncelleme zamanına göre çözülür.'],['Hafızayı silme','Bu araca ait tarayıcı kayıtlarını kaldırır; cihazdaki dışa aktarılmış dosyaları silmez.'],['Karar sınırı','Puanlar deprem güvenliği olasılığı değildir; yalnız gözlemsel kanıt ağırlığıdır.']].map(x=>`<section class="helpblock"><h2>${x[0]}</h2><p>${x[1]}</p></section>`).join('')}</div>`;
})();
